# Generated by Django 5.2.8 on 2025-11-28 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_style', models.CharField(default='Abstract & Dreamy', max_length=100)),
                ('caption_tone', models.CharField(default='Reflective & Poetic', max_length=100)),
                ('include_audio', models.BooleanField(default=True)),
                ('output_format', models.CharField(default='IMAGE', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FriendProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('personality', models.TextField()),
                ('context', models.TextField()),
                ('voice_name', models.CharField(max_length=50)),
                ('avatar_url', models.URLField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('content', models.TextField()),
                ('mood', models.CharField(choices=[('GREAT', 'Great'), ('GOOD', 'Good'), ('NEUTRAL', 'Neutral'), ('STRESSED', 'Stressed'), ('BAD', 'Bad')], max_length=20)),
                ('ai_reflection', models.TextField(blank=True, null=True)),
                ('tags', models.JSONField(default=list)),
                ('attachments', models.JSONField(default=list)),
                ('type', models.CharField(default='text', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('completed', models.BooleanField(default=False)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10)),
                ('subject', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FeedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.TextField(blank=True)),
                ('video_url', models.TextField(blank=True)),
                ('caption', models.TextField()),
                ('likes', models.IntegerField(default=0)),
                ('is_liked', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('mood_tag', models.CharField(max_length=20)),
                ('audio_data', models.TextField(blank=True, null=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='api.journalentry')),
            ],
        ),
    ]
