# Generated by Django 5.2.8 on 2025-11-28 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='attachments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
