# Generated by Django 5.2.8 on 2025-11-29 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_journalentry_attachments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='include_in_feed',
            field=models.BooleanField(default=True),
        ),
    ]
