# Generated by Django 5.2.8 on 2025-11-29 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_journalentry_include_in_feed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='context',
            field=models.CharField(blank=True, choices=[('PERSONAL', 'Personal'), ('PROFESSIONAL', 'Professional'), ('MIXED', 'Mixed')], default='PERSONAL', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='context_score',
            field=models.IntegerField(blank=True, default=50),
        ),
        migrations.AddField(
            model_name='task',
            name='energy_level',
            field=models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10),
        ),
        migrations.AddField(
            model_name='task',
            name='estimated_duration_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='external_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='subtasks',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
