# Generated by Django 5.2.8 on 2025-11-29 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_task_category_task_context_task_context_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PERSON', 'Person'), ('EVENT', 'Event'), ('FEELING', 'Feeling')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('media_url', models.URLField(blank=True, max_length=500, null=True)),
                ('accumulated_context', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EntityInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_snippet', models.TextField()),
                ('sentiment_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='api.entity')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_interactions', to='api.journalentry')),
            ],
        ),
    ]
