# Generated by Django 5.2.8 on 2025-11-30 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_entity_entityinteraction'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('DIARY', 'Diary Entry'), ('MEMORY', 'Memory'), ('SYSTEM', 'System Generated')], max_length=20)),
                ('source_id', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField()),
                ('meta_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('likes', models.IntegerField(default=0)),
                ('is_liked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FeedSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='default_user', max_length=100)),
                ('show_diary_entries', models.BooleanField(default=True)),
                ('show_memories', models.BooleanField(default=True)),
                ('show_system_content', models.BooleanField(default=True)),
            ],
        ),
    ]
